### ISSUE TITLE
CMake v3.30.0 is not supported. Compatibility with future CMake versions is to be verified.

### ISSUE THREAD

**Issue by harrymash2006** [birdofpreyru/react-native-static-server#111] opened 2024-07-09 17:20 UTC
const prepareAssets = async () => {
    try {
      const fileDir = resolveAssetsPath('webroot');
      const filePath = fileDir + '/index.html';
      if (Platform.OS === 'ios') {
        await modifyContent(filePath);
      }
      if (Platform.OS === 'android') {
        console.log('fileDir:: inside android::', fileDir);
        const alreadyExtracted = await exists(fileDir);
        console.log('fileDir:: alreadyExtracted::', alreadyExtracted);
        if (alreadyExtracted) {
          await unlink(fileDir);
        }
        console.log('fileDir:: before copy assets::');
        await copyFileAssets('webroot', fileDir);
        console.log('fileDir:: before read file::');
        await modifyContent(filePath);
      }
      return fileDir;
    } catch (e) {
      console.log('fileDir:: exception::', e);
    }
    return null;
  };
  
  Please help.

**Comment by birdofpreyru** [comment] 2024-07-10 07:14
It reads like you failed to follow README and correctly bundle in the `webroot` asset folder you are trying to access. In addition to README the repo contains [Example App](https://github.com/birdofpreyru/react-native-static-server/tree/master/example) demonstrating how to do it correctly.

**Comment by harrymash2006** [comment] 2024-07-10 10:12
Hi @birdofpreyru I followed the same instructions and did the same code as the example app but I am getting the same issues. I ended up using a document directory thing and writing things manually to that path and then using that path for the server and got it working. 

I am facing some other issue that is unrelated to this but when I try to build the app after selecting "Any iOS Device (arm64)" option I get the following error: 

```
CMake Error at /opt/homebrew/Cellar/cmake/3.30.0/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:129 (message):
  The C compiler targets architectures:

    "arm64"

  but CMAKE_OSX_ARCHITECTURES is

    "arm64;x86_64"

Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.30.0/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:109 (project)


-- Configuring incomplete, errors occurred!
CMake Error at CMakeLists.txt:72 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"
```

can you please help @birdofpreyru? 

thanks, I really appreciate it.

**Comment by birdofpreyru** [comment] 2024-07-10 10:39
Does the [Example app](https://github.com/birdofpreyru/react-native-static-server/tree/master/example) build for you?

**Comment by harrymash2006** [comment] 2024-07-10 10:44
No, actually I am getting some different errors when running sample app on simulator. 

My app works fine on simulator but I get this error when I try to run it on a real device or try to build for publishing for the store which uses only arm64, where CMAKE_OSX_ARCHITECTURES expects architecture "arm64;x86_64"

**Comment by birdofpreyru** [comment] 2024-07-10 10:47
> _No, actually I am getting some different errors when running sample app on simulator._

What errors do you get when running the sample app?

> My app works fine on simulator but I get this error when I try to run it on a real device or try to build for publishing for the store which uses only arm64, where CMAKE_OSX_ARCHITECTURES expects architecture "arm64;x86_64"

Any errors in your app, which aren't present in the Example App, are you problems to solve &mdash; I am not going to do your development work for you for free.

**Comment by harrymash2006** [comment] 2024-07-10 11:06
<img width="1100" alt="Screenshot 2024-07-10 at 4 36 20 PM" src="https://github.com/birdofpreyru/react-native-static-server/assets/5957516/81e6ac88-12c3-4504-b061-3d62f5d234fe">

I am getting the above error when I try to run the app on a real device.

**Comment by harrymash2006** [comment] 2024-07-10 11:38
Hi @birdofpreyru any update on the above?

**Comment by birdofpreyru** [comment] 2024-07-10 12:33
Do you get this error when building the Example app?

**Comment by harrymash2006** [comment] 2024-07-10 12:42
yes
*Thanks,*
*Hardik Mashru*
Expert Mobile Developer | React Native, Android, iOS, Flutter, Java, J2EE,
Restful Web Services, Core PHP, Struts, Hibernate

**Comment by birdofpreyru** [comment] 2024-07-10 12:45
Ok, I’ll re-recheck example app build for iOS when I find time.

**Comment by harrymash2006** [comment] 2024-07-10 12:52
Android build is working fine, only having issues with iOS. I am trying on macOS machine.

**Comment by martinezleoml** [comment] 2024-07-13 08:12
We're also facing the issue, it sounds like a regression bug with the latest CMake version (3.30) & Xcode builds: https://gitlab.kitware.com/cmake/cmake/-/issues/26128

Downgrading to CMake 3.29.6 solves the issue. ;)

**Comment by birdofpreyru** [comment] 2024-07-13 13:03
It seems to be a regression in CMake 3.30.0:
- A thread in CMake forum: https://discourse.cmake.org/t/cmake-3-30-doesnt-let-me-use-archs-standard-to-set-cmake-osx-architectures/11209
- The issue in CMake repo: thttps://gitlab.kitware.com/cmake/cmake/-/issues/26128

**Comment by birdofpreyru** [comment] 2024-07-13 14:54
Ok, starting with [v0.15.1](https://github.com/birdofpreyru/react-native-static-server/releases/tag/v0.15.1) this library will refuse to be built with CMake v3.30.0 on all platforms, with a clear error message pointing back to this issue.

l keep this issue ticket open, and marked as _In Progress_ and _On Hold_, to remind myself to check back if the issue is resolved in future CMake versions.

**Comment by birdofpreyru** [comment] 2024-07-28 12:54
Heads-up: it seems to be still broken with CMake v3.30.1; and, presumably, it is aimed to be fixed in CMake v3.30.2.

**Comment by niryuu** [comment] 2024-08-11 21:20
This is reproduced on CMake v3.30.2 installed via Homebrew.

**Comment by niryuu** [comment] 2024-08-11 22:13
I do not know well about CMake, and why we need `ESCAPED_ARCHS`, but modifying CMakeLists.txt as below works.
from
`-DCMAKE_OSX_ARCHITECTURES=${ESCAPED_ARCHS}`
to
`-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}`

**Comment by birdofpreyru** [comment] 2024-08-12 08:02
Yeah, as [the CMake ticket](https://gitlab.kitware.com/cmake/cmake/-/issues/26128) is closed now, I guess we need some corrections in our `CMakeLists.txt`.

> _why we need `ESCAPED_ARCHS`_

as [the comment](https://github.com/birdofpreyru/react-native-static-server/blob/6da88a8e997a23294c2a7587a6dd62b767be25c5/CMakeLists.txt#L22-L29) says, without an escape of `;` CMake replaced it by a whitespace when `EXTRA_BUILD_ARGS` was added to the `COMMAND` piece of `execute_process()`, thus effectively the command was run with `-DCMAKE_OSX_ARCHITECTURES=arm64 x86_64` instead of `-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64`, which resulted in PCRE2 built only for the first arch in the list, rather than for each one, and an error down the line when the built failed to link against PCRE2 built for the target architecture.

So, although the change you did seemingly worked, you really want to verify for what architectures PCRE2 library got built, and perhaps a different change is needed. I am not an expert in CMake either, though, so can't give much help, until I find a moment to dive into it myself.

**Closed** 2024-09-19 23:00 UTC
Labels: P0 !!!, Ready

**Comment by niryuu** [comment] 2024-09-25 05:50
FYI: It works on CMake 3.30.3.  Hence This problems seems to occur only on 3.30.0-2.

**Comment by birdofpreyru** [comment] 2024-09-25 07:46
Yes, that's why this ticket was closed ;)
