### ISSUE TITLE
The iOS release assembly is not going to build.

### ISSUE THREAD

**Issue by belyylis** [birdofpreyru/react-native-static-server#76] opened 2023-10-09 13:38 UTC
![Снимок экрана 2023-10-09 в 16 35 47](https://github.com/birdofpreyru/react-native-static-server/assets/58907138/c908e270-3a27-453e-8e87-32d8029c0131)
![Снимок экрана 2023-10-09 в 16 36 06](https://github.com/birdofpreyru/react-native-static-server/assets/58907138/16cac981-737f-4548-9b83-0147e0eeeaec)
Could you tell me how to fix this? CMake is installed, the latest version of the library.
Mac on M1.

**Comment by birdofpreyru** [comment] 2023-10-09 15:51
It looks like a duplicate of #67. In my current understanding, on M1 Mac it is not enough to just install CMake and pkg-config, they should be correctly symlinked, or perhaps added to `.xcode.env` file of the project, to become visible inside Xcode environment. It is both written in README, and discussed in that other issue ticket.

**Closed by birdofpreyru** 2023-10-09 15:51 UTC
